### ISSUE TITLE
General code cleanup

### ISSUE THREAD

**Issue by szymach** [fsi-open/admin-bundle#262]
TODO:
- [x] Remove docblocks in specs in favour of class typehints. (#261)
- Check specs for outdated or improper checks. (Moved to #281)
- [x] Resolve [SensioLabs insight issues](https://insight.sensiolabs.com/projects/82a9e680-cff7-460b-973c-67a2fc7adac0). (#264)
- [x] Refactor and update Behat contexts. (Start at #264, concludes at #267)
- [x] Remove Selenium for batch element Behat features.
- [x] Short array syntax.
